//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatVeXemPhim.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actor
    {
        public int IDActor { get; set; }
        public string NameActor { get; set; }
    }
}
